services:

  web:
    image: timeclock:1
    container_name: timeclock
    restart: always
    volumes:
      - .:/app
    command:  gunicorn --bind 0.0.0.0:5000 --threads 3 app:app
    ports:
      - 5050:5000